name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        GITHUB_PAGES: true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Build frontend
        run: |
          pnpm install
          pnpm --filter frontend build
      - name: Move build output
        run: |
          mkdir -p ./dist
          cp -r packages/frontend/dist/* ./dist
      - name: Setup pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
